# NumPy
## ndarray sorting

In [2]:
import numpy as np
arr = np.ndarray(shape=(10,10), dtype=int, order='F')
a = np.array([('a', 2), ('c', 1)], dtype=[('x', 'S1'), ('y', int)])
arr.sort(axis=0) # This is relevant
arr

array([[            27331328,   753057079118094712,   748834950222015790,
             113739410505728, -8038362384898756096, -6845335087181958144,
         2308708857841611361,   723441445811352178,  2308668953702003314,
         2314885530818447973],
       [            27331328,  2314885436548132141,  2323362894317625376,
           13073193254280818,           5955911680,                    0,
         2325032996649902182,  2308784694146393453,  2308707431035514157,
         7018051270194110565],
       [     139704662327984,  3255307777494491168,  3184145384580595262,
          732223240535370611,         341215019008,          12884901890,
         2334102019056430368,  2314861397616176429,  2314861724910645857,
         7163375924030107424],
       [     139704662327984,  4404627226679459360,  3472601203671458162,
         2314885530447928617,         843726192640,       33479270072387,
         7143307423181185056,  2336927755148816928,  2324174205049905184,
         7305798935

In [30]:
arr = np.ndarray(shape=(10,10), dtype=int)
sum(sum(arr))

13148621604353008

In [5]:
np.ones(shape=(3, 3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [13]:
m = np.random.rand(4, 3)
m

array([[0.25121377, 0.22947432, 0.18968366],
       [0.75553707, 0.09717432, 0.24342275],
       [0.16084961, 0.25312596, 0.00254757],
       [0.92891262, 0.07489568, 0.35544328]])

In [17]:
np.rot90(m)

array([[0.18968366, 0.24342275, 0.00254757, 0.35544328],
       [0.22947432, 0.09717432, 0.25312596, 0.07489568],
       [0.25121377, 0.75553707, 0.16084961, 0.92891262]])

In [19]:
m2 = np.random.rand(3, 4)
np.matmul(m, m2)

array([[0.11029644, 0.34454889, 0.3615742 , 0.31997908],
       [0.15973132, 0.59130406, 0.51217364, 0.77535047],
       [0.09755368, 0.16577806, 0.21264003, 0.17670597],
       [0.18521646, 0.75474611, 0.64191786, 0.96727012]])