## Exercises NumPy

### NumPy

Please solve the following exercises. If necessary provide test cases:\
a) Create a NumPy Array "a" of size 50 with random numbers between 0 and 100.\
b) Create a NumPy Array "b" of size 10*10 with random numbers less than 0.\
c) Calculate the sum and average of each column and each row of "b".\
d) Print all values of "a" that are greater than 1 but smaller than 6. How many percent of the numbers are in that range?\
e) Create a NumPy Array "c" of size 30 with the repeating sequence "1, 2, 3, 4".\
f) Create a 3×3 NumPy Array "d" of all True’s\
g) Extract all odd numbers from "a".\
h) Write a NumPy program to get the powers of an array values element-wise. (First element to the power of the second element, second element to the power of the third element, ...).\
i) Write a NumPy program to multiply a 5x3 matrix by a 3x2 matrix and create a real matrix product.\
j) Write a NumPy program to convert angles from degrees to radians for all elements in a given array.\
k) Find all the peaks in "a". Peaks are points surrounded by smaller values on both sides.\
l) Given an array of a non-continuous sequence of dates. Make it a continuous sequence of dates, by filling in the missing dates.\
m) Create a rank array of the same shape as "b".\
n) Write a function that has a 2D array as input parameter. If this matrix is squared and its shape is a square number return sliced arrays (horizontal and vertical) with size of the square root of the dimenstions. If this matrix is not squared return an information why the operation could not be performed.\
o) Provide an overview of the frequency of each number of "b".\
p) Solve the system of equations:\
$$4x + 3y + 2z = 25$$
$$-2x + 2y + 3z = -10$$
$$3x -5y + 2z = -4$$

Data for exercise l)

In [1]:
import numpy as np
dates = np.arange(np.datetime64('2020-04-01'), np.datetime64('2020-04-30'), 2)
dates

array(['2020-04-01', '2020-04-03', '2020-04-05', '2020-04-07',
       '2020-04-09', '2020-04-11', '2020-04-13', '2020-04-15',
       '2020-04-17', '2020-04-19', '2020-04-21', '2020-04-23',
       '2020-04-25', '2020-04-27', '2020-04-29'], dtype='datetime64[D]')

a) *Your code...*

In [5]:
a = np.random.randint(0, 101, size=50)
a

array([60, 54,  9, 94, 27, 55, 34, 32, 44, 40, 75, 59, 89, 95, 78, 57, 30,
       98, 96, 27, 22, 93, 40, 94,  5, 41, 30,  2, 33, 96, 23, 76, 80, 77,
       33, 89,  5, 68, 21, 59, 45, 22, 60, 11,  6, 75, 60,  1, 64, 15])

b) *Your code...*

In [8]:
b = np.random.randint(-100, 0, size=(10, 10))
b

array([[ -83,   -6,  -81,  -97,  -67,  -32,  -31,  -64,  -29,   -4],
       [ -64,  -67,  -45,  -32,   -9,  -33,  -81, -100,  -65,  -20],
       [ -42,  -36,  -11,  -29,  -56,  -90,  -78,  -23,   -7,  -62],
       [ -69,  -81,  -14,  -77,  -44,  -97,  -93,  -10,  -51,  -60],
       [ -27,  -21,  -53,  -47,  -59,  -66,  -15,  -27,  -68,  -20],
       [ -79,  -63,  -35,   -3,  -34,  -50,  -92,  -47,  -15,  -66],
       [ -95,  -11,  -20,  -55,  -87,  -97,  -63,  -35,  -66,  -50],
       [ -24,  -66,  -71,  -80,  -10,   -6,  -78,  -76,  -78,  -59],
       [ -22,  -41,  -46,  -83,  -81,  -20,  -61,  -11,  -26,  -84],
       [ -22,   -9,   -9,  -54,  -83,  -41,  -67,  -56,  -93,  -40]])

c) *Your code...*

In [9]:
display(np.sum(b))
display(np.sum(b, axis=0))
display(np.average(b))
display(np.average(b, axis=0))

-5003

array([-527, -401, -385, -557, -530, -532, -659, -449, -498, -465])

d) *Your code...*

In [10]:
res = a[(a > 1) & ( a < 6)]
print(f"res: {res}, {len(res) / len(a)}")

res: [5 2 5], 0.06


e) *Your code...*

In [11]:
c = np.resize(np.arange(1,5), 30)
c

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2,
       3, 4, 1, 2, 3, 4, 1, 2])

f) *Your code...*

In [13]:
d = np.full((3,3), True)
d

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

g)  Extract all odd numbers from “a”

In [14]:
a[a % 2 == 1]

array([ 9, 27, 55, 75, 59, 89, 95, 57, 27, 93,  5, 41, 33, 23, 77, 33, 89,
        5, 21, 59, 45, 11, 75,  1, 15])

h) Write a NumPy program to get the powers of an array values element-wise. (First element to the power of the second element, second element to the power of the third element, ...).

In [15]:
elements = np.array([0, 1, 2, 3, 4, 5])
np.power(elements, np.roll(elements, -1))
#np.roll(elements, -1)

array([1, 2, 3, 4, 5, 0])

i) Write a NumPy program to multiply a 5x3 matrix by a 3x2 matrix and create a real matrix product.

In [9]:
def matrix_mult(x1, x2):
    return np.matmul(x1, x2)
x1 = np.random.random((5, 3))
x2 = np.random.random((3, 2))
matrix_mult(x1, x2)

array([[0.67323434, 0.82069568],
       [1.07368453, 1.21532487],
       [0.83356427, 1.08735871],
       [0.4069558 , 0.83931212],
       [1.26525585, 1.31275029]])

j) Write a NumPy program to convert angles from degrees to radians for all elements in a given array.

In [16]:
def deg2rad(degs):
    return np.deg2rad(degs)

deg2rad(np.array([90, 180, 360]))

array([1.57079633, 3.14159265, 6.28318531])

k) Find all the peaks in "a". Peaks are points surrounded by smaller values on both sides.

In [18]:
for i in range(len(a)):
    if a[i-1] < a[i] > a[(i + 1) % len(a)]:
        print(f"Peak: {a[i]} at {i}")

Peak: 60 at 0
Peak: 94 at 3
Peak: 55 at 5
Peak: 44 at 8
Peak: 75 at 10
Peak: 95 at 13
Peak: 98 at 17
Peak: 93 at 21
Peak: 94 at 23
Peak: 41 at 25
Peak: 96 at 29
Peak: 80 at 32
Peak: 89 at 35
Peak: 68 at 37
Peak: 59 at 39
Peak: 60 at 42
Peak: 75 at 45
Peak: 64 at 48


l) Given an array of a non-continuous sequence of dates. Make it a continuous sequence of dates, by filling in the missing dates.

In [20]:
l = np.arange(min(dates), max(dates), dtype="datetime64[D]")
l

array(['2020-04-01', '2020-04-02', '2020-04-03', '2020-04-04',
       '2020-04-05', '2020-04-06', '2020-04-07', '2020-04-08',
       '2020-04-09', '2020-04-10', '2020-04-11', '2020-04-12',
       '2020-04-13', '2020-04-14', '2020-04-15', '2020-04-16',
       '2020-04-17', '2020-04-18', '2020-04-19', '2020-04-20',
       '2020-04-21', '2020-04-22', '2020-04-23', '2020-04-24',
       '2020-04-25', '2020-04-26', '2020-04-27', '2020-04-28'],
      dtype='datetime64[D]')

m) *Your code...*

n) Write a function that has a 2D array as input parameter. If this matrix is squared and its shape is a square number return sliced arrays (horizontal and vertical) with size of the square root of the dimensions. If this matrix is not squared return an information why the operation could not be performed.

In [12]:
def sliced_square_array(matrix):
    (x, y) = matrix.shape
    if x != y:
        return 'Not square'
    is_square = x ** 0.5 % 1 == 0
    if not is_square:
        return 'Dimension not square'
    return matrix[0:x ** 0.5, 0:x ** 0.5]
sliced_square_array(np.random.random((9, 9)))

matrix([[3., 3.]])

o) *Your code...*

In [ ]:
a, count = np.unique(b, return_counts=True)
print(f"{a}: {count}")

p) *Your code...*